<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.1</TargetFrameworks>
    <OutputType>Library</OutputType>
    <AssemblyName>AOSharp.Common.Unmanaged</AssemblyName>
    <RootNamespace>AOSharp.Common.Unmanaged</RootNamespace>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <BaseOutputPath>$(MSBuildProjectDirectory)\..\bin</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Reloaded.Hooks.Definitions" Version="1.15.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AOSharp.Common\AOSharp.Common.csproj" />
  </ItemGroup>
</Project>
